# Generated by Django 4.2.26 on 2025-12-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('service', models.CharField(blank=True, max_length=255, verbose_name='Интересующая услуга')),
                ('message', models.TextField(blank=True, verbose_name='Комментарий')),
                ('form_context', models.CharField(choices=[('main', 'Главная страница'), ('services', 'Страница услуг'), ('contacts', 'Контакты'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Откуда пришла заявка')),
                ('page_url', models.CharField(blank=True, max_length=500, verbose_name='Страница (URL)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
        ),
    ]
