# Generated by Django 4.2.26 on 2025-12-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='lead',
            name='form_context',
            field=models.CharField(blank=True, help_text='Откуда отправили: contacts_page, index_page, doctors_page и т.д.', max_length=100, verbose_name='Источник формы'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='page_url',
            field=models.URLField(blank=True, verbose_name='Страница отправки'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='service',
            field=models.CharField(blank=True, max_length=255, verbose_name='Услуга / тема'),
        ),
    ]
