# Generated by Django 4.2.26 on 2025-12-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_lead_options_alter_lead_form_context_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='form_context',
            field=models.CharField(blank=True, help_text='Например: index_hero, doctors_page, contacts_page', max_length=100, verbose_name='Источник формы'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='page_url',
            field=models.URLField(blank=True, help_text='URL, откуда отправили форму', verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='service',
            field=models.CharField(blank=True, max_length=150, verbose_name='Услуга / тема'),
        ),
    ]
