# Generated by Django 4.2.26 on 2025-12-01 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_lead_form_context_alter_lead_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Слаг')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория услуги',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('slug', models.SlugField(help_text='Например: dental, pediatrics, neurology', max_length=200, unique=True, verbose_name='Слаг (для service-detail)')),
                ('short_intro', models.CharField(blank=True, help_text='1–2 строки, которые видны в списке услуг.', max_length=300, verbose_name='Краткое описание (карточка)')),
                ('description', models.TextField(blank=True, help_text='Текст для service-detail страницы.', verbose_name='Подробное описание')),
                ('duration', models.CharField(blank=True, help_text='Например: 30–40 минут', max_length=100, verbose_name='Длительность приёма')),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, help_text='Минимальная стоимость, можно оставить пустой.', max_digits=10, null=True, verbose_name='Цена от')),
                ('tags', models.CharField(blank=True, help_text='Например: детский приём, профилактика, консультация', max_length=300, verbose_name='Теги (через запятую)')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярная услуга')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в списке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='clinic.servicecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order', 'title'],
            },
        ),
    ]
